name: Daily Job Scraper

on:
  # Run daily at 9 AM IST (3:30 AM UTC)
  schedule:
    - cron: '30 3 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to main branch (for testing)
  push:
    branches: [ main ]

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run job scraper
      run: |
        python scraper.py
        
    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Auto-update: $(date '+%Y-%m-%d %H:%M:%S')"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        
    - name: Upload job results
      uses: actions/upload-artifact@v4
      with:
        name: job-results-${{ github.run_number }}
        path: |
          *.csv
          *.json
          *.txt
        retention-days: 30
